services:
  app:
    image: search-similar-videos:latest
    container_name: search-similar-videos
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
    restart: no
